### ISSUE TITLE
License is misssing

### ISSUE THREAD

**Issue by asomsiko** [esnet/dpdk-plugin#7]
https://github.com/esnet/dpdk-plugin/blob/main/COPYING.edit-me seems a license boilerplate.

@grigorescu could you, please, define a license? It should be enough to remove `edit-me` extension and fill in the missing fields so dpdk-plugin can be included in the other projects. Ideally, GitHub UI should display "BSD-3-Clause-License" like here https://github.com/hosom/file-extraction

**Comment by asomsiko** [comment]
@tbarbette, @dwcarder @sartaj10 @grigorescu could define a license for ESNet dpdk-plugin so that it can be used by others.

**Comment by tbarbette** [comment]
I just did one PR after randomly arriving on this repo to try to accelerate Zeek a bit. I can't help with this, sorry.

**Comment by dopheide-esnet** [comment]
Updated the LICENSE.  Let me know if there's anything else I can help with.
